apiRules:
- include:
    uidRegex: ^tower-defense
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- include:
    uidRegex: ^Tests
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace